In [1]:
# /*==========================================================================================*\
# **                        _           _ _   _     _  _         _                            **
# **                       | |__  _   _/ | |_| |__ | || |  _ __ | |__                         **
# **                       | '_ \| | | | | __| '_ \| || |_| '_ \| '_ \                        **
# **                       | |_) | |_| | | |_| | | |__   _| | | | | | |                       **
# **                       |_.__/ \__,_|_|\__|_| |_|  |_| |_| |_|_| |_|                       **
# \*==========================================================================================*/


# -----------------------------------------------------------------------------------------------
# Author: Bùi Tiến Thành (@bu1th4nh)
# Title: playground_numpy.ipynb
# Date: 2024/09/22 14:52:56
# Description: Testing lab for Numpy and Pandas
# 
# (c) bu1th4nh. All rights reserved
# -----------------------------------------------------------------------------------------------


import numpy as np
import pandas as pd

import mlflow


mlflow.set_tracking_uri(uri="http://127.0.0.1:6969")
mlflow.set_experiment("SimilarSampleCrossOmicNMFv3")


with mlflow.start_run(run_id="0b7f21f1612b4ebe8e709502a9fc8933"):
    pass



2024/11/07 15:33:25 INFO mlflow.tracking._tracking_service.client: 🏃 View run baseline-norm_baseline at: http://127.0.0.1:6969/#/experiments/436914505726212499/runs/0b7f21f1612b4ebe8e709502a9fc8933.
2024/11/07 15:33:25 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:6969/#/experiments/436914505726212499.


In [2]:
Ariel = [
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
]


size_list = [1, 3, 4]

Belle = [
    list(np.hsplit(horizontal_block, size_list))
    for horizontal_block 
    in np.vsplit(Ariel, size_list)
]


print(np.block(Belle))
print()
print(np.block(Belle) - Ariel)
print()
for hblk in Belle:
    print("  ".join(f"{blk.shape}" for blk in hblk))
print()

for i, row in enumerate(Belle):
    for j, col in enumerate(row):
        print(f"block {i+1}-{j+1}")
        print(col)
        print("----")

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

(1, 1)  (1, 2)  (1, 1)  (1, 1)
(2, 1)  (2, 2)  (2, 1)  (2, 1)
(1, 1)  (1, 2)  (1, 1)  (1, 1)
(1, 1)  (1, 2)  (1, 1)  (1, 1)

block 1-1
[[1]]
----
block 1-2
[[2 3]]
----
block 1-3
[[4]]
----
block 1-4
[[5]]
----
block 2-1
[[1]
 [1]]
----
block 2-2
[[2 3]
 [2 3]]
----
block 2-3
[[4]
 [4]]
----
block 2-4
[[5]
 [5]]
----
block 3-1
[[1]]
----
block 3-2
[[2 3]]
----
block 3-3
[[4]]
----
block 3-4
[[5]]
----
block 4-1
[[1]]
----
block 4-2
[[2 3]]
----
block 4-3
[[4]]
----
block 4-4
[[5]]
----


In [3]:
Ariel = [
    [1, 69, 1, 1, 1],
    [1, 0, 1, 1, 1],
    [0, 0, 0, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 0, 0, 0],
]

print(np.sum(Ariel, axis=1))
print(np.diag(np.sum(Ariel, axis=1)))
print(np.diag(1/(np.sqrt(np.sum(Ariel, axis=1)))))

[73  4  2  2  1]
[[73  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  2  0  0]
 [ 0  0  0  2  0]
 [ 0  0  0  0  1]]
[[0.11704115 0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.        ]
 [0.         0.         0.70710678 0.         0.        ]
 [0.         0.         0.         0.70710678 0.        ]
 [0.         0.         0.         0.         1.        ]]


In [4]:
Ariel = [
    [1, 69, 1, 1, 1],
    [1, 0, np.nan, 1, 1],
    [0, 0, 0, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 0, 0, np.nan],
]

nan_list = np.argwhere(np.isnan(Ariel))
print(nan_list)

[[1 2]
 [4 4]]


In [5]:
log_file = '/home/ti514716/Projects/SimilarSampleCrossOmicNMF/crossomic_mini_02.log'


# read log file line by line
with open(log_file, 'r') as f:
    lines = f.readlines()
print(lines[0])

import re
import numpy as np

# extract iteration number and loss value
losses = []
deltas = []
for line in lines:
    match = re.search(r'Objective function = (\d+\.\d+)', line)
    if match:
        loss = float(match.group(1))
        losses.append(loss)

    match = re.search(r'delta =', line)
    if match:
        delta = float(line.split('delta = ')[-1].split(' ')[0])
        deltas.append(delta)
losses = np.array(losses)
deltas = np.array(deltas)[100:]


import matplotlib.pyplot as plt
plt.figure(figsize=(20, 5))
plt.plot(losses)
plt.xlabel('Iteration')
plt.ylabel('Loss')
plt.title('Loss curve')
plt.show()

plt.figure(figsize=(20, 5))
plt.plot(np.log(np.abs(deltas)), color='red')
plt.xlabel('Iteration')
plt.ylabel('Delta, log scale (10^x)')
plt.title('Changes per iteration for objective function (log scale, absolute value)')
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: '/home/ti514716/Projects/SimilarSampleCrossOmicNMF/crossomic_mini_02.log'

In [ ]:
import pandas as pd

Ariel = pd.read_parquet('/home/ti514716/Projects/SimilarSampleCrossOmicNMF/results/v3/k-10-alpha-100-beta-1-gamma-overridden/classification_result.parquet')
Ariel

In [ ]:
import numpy as np


X = [
    np.array(
        [
            [1, 2, 3, 4, 5],
            [1, 2, 3, 4, 5],
            [1, 2, 3, 4, 5],
            [1, 2, 3, 4, 5],
        ]
    ),
    np.array(
        [
            [4, 5, 6, 7, 8],
            [4, 5, 6, 7, 8],
        ]
    ),
]

H = np.array(
    [
        [2, 3, 8, 1, 6],
        [2, 3, 8, 1, 6],
    ]
)

N = X[0].shape[1]
m = [x.shape[0] for x in X]
D = len(X)
k = 2

print(N, m)


Cinderella = X[0].flatten(order='F')
print(Cinderella)

print(Cinderella.reshape((m[0], N), order='F'))

In [ ]:
for d in range(D):
    Ariel = X[d].flatten(order='F')
    print(Ariel)
    print(Ariel.shape)

    print()

    Belle = np.kron(np.eye(m[d]), H.T)
    print(Belle)
    print(Belle.shape)


    from sklearn.linear_model import LassoCV
    lasso = LassoCV().fit(Belle, Ariel)

    print()
    print(np.array(lasso.coef_).reshape(-1, k))
    print()
    print(lasso.alphas_.shape)
    print()
    print()


In [ ]:
import numpy as np

Aurora = np.array([[1, 2], [3, 4], [3, 6]])
print(Aurora)

print(np.linalg.norm(Aurora, ord=1, axis=0))  # Normalize by column


print(Aurora / np.linalg.norm(Aurora, ord=1, axis=0))

[[1 2]
 [3 4]
 [3 6]]
[ 7. 12.]
[[0.14285714 0.16666667]
 [0.42857143 0.33333333]
 [0.42857143 0.5       ]]


In [13]:
import cupy as cp
x = cp.arange(73117828)
x.sum(axis=0)



array(2673108349159878)